config/routes.rb
Rails.application.routes.draw do
  get 'notifications/link_through'
  resources :posts do
    resources :replies
    resources :likes
  end

  resources :conversations do
    resources :messages
  end


  resources :profiles

  get "search", to: "posts#search"
  get "geolocation", to: "posts#geolocation"
  get "faq", to: "public#faq"
  get "secret", to: "conversations#secret"
  get 'notifications', to: 'notifications#index'
  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through


  devise_for :accounts, :controllers => { :omniauth_callbacks => "omniauth_callbacks", registrations: 'registrations'}
  root "public#main"
end

app/models/reply.rb
class Reply < ApplicationRecord
belongs_to :post
belongs_to :account
validates :reply, presence: true
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  before_action :authenticate_account!
  before_action :set_reply, only: [:edit, :update, :show, :destroy]
  before_action :set_post, only: [:create, :edit, :show, :update, :destroy]
  before_action :owned_reply, only: [:edit, :update, :destroy]

  def create
    @reply = @post.replies.create(params[:reply].permit(:reply, :post_id))
    @reply.account_id = current_account.id

    if @reply.save
        create_notification(@post)
        respond_to do |format|
            format.html { redirect_to post_path(@post) }
            format.js # renders create.js.erb
        end
    else
        format.html { redirect_to post_path(@post), notice: "Commento non inserito, riprova."}
        format.js
    end
  end

  def new
  end

  def destroy
    @reply = @post.replies.find(params[:id])
    @reply.destroy
    redirect_to post_path(@post)
  end

  def edit
    @post = Post.find(params[:post_id])
    @reply = @post.replies.find(params[:id])
  end

  def update
    @reply = @post.replies.find(params[:id])
     respond_to do |format|
      if @reply.update(reply_params)
        format.html { redirect_to post_path(@post), notice: 'Commento modificato correttamente' }
      else
        format.html { render :edit }
        format.json { render json: @reply.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_reply
    @reply = Reply.find(params[:id])
  end

  def reply_params
    params.require(:reply).permit(:reply)
  end

  def owned_reply
        unless current_account == @reply.account || current_account.has_role?(:admin) || current_account == @reply.post.account
            flash[:alert] = "Non hai i privilegi necessari per accedere a questa funzione"
            redirect_to posts_path
        end
  end

  def create_notification(post)
    Notification.create(account_id: post.account.id, notified_by_id: current_account.id, post_id: post.id, notice_type: 'commentato')
  end

end

app/views/replies/_form.html.erb
<%= simple_form_for([@post, @post.replies.build], remote: true) do |f| %>

<div class="field">
  <div class="control">
    <%= f.input :reply, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: 'label' } %>
  </div>
</div>

<%= f.button :submit, 'Rispondi', class:'button is-info' %>

<% end %>

app/views/replies/_reply.html.erb
<div class="box">
  <article class="media">
    <div class="media-left">
      <figure class="image is-48x48">
        <%= gravatar_image_tag(reply.account.email, class: 'border-radius-50', size: 48, alt: reply.account.username) %>
      </figure>
    </div>
    <div class="media-content">
      <div class="content">
        <p>
          <strong><%=link_to(reply.account.first_name + " " + reply.account.last_name, profile_path(reply.account_id) )%></strong> <br/><small><%= time_ago_in_words(reply.created_at) %> ago</small>
          <br/>
          <%= reply.reply %>
        </p>
      </div>
      <% if current_account.id == reply.account_id || has_role?(:admin) || current_account.id == reply.post.account_id %>
      <nav class="level is-mobile">
        <div class="level-left">
          <a class="level-item">
            <%= link_to edit_post_reply_path(reply.post, reply) do %>
            <span class="icon is-small"><i class="fa fa-pencil"></i></span>
            <% end %>
          </a>
          <a class="level-item">
            <%= link_to [reply.post, reply],
                method: :delete, data: {confirm: "Sei sicuro ?" } do %>
            <span class="icon is-small"><i class="fa fa-trash-o"></i></span>
            <% end %>
          </a>
        </div>
      </nav>
    <% end %>
    </div>
  </article>
</div>

app/views/replies/create.js.erb
$("<%= escape_javascript(render(@reply)) %>").appendTo('#post-replies');

app/views/replies/edit.html.erb
<section class="form-auth text-center">
<h1 class="title is-2 has-text-grey">Modifica commento</h1>

<%= simple_form_for([@post, @reply]) do |f| %>
<div class="field">
  <div class="control">
    <%= f.input :reply, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: 'label' } %>
  </div>
</div>

  <%= f.button :submit, 'Modifica', class:'button is-info' %>
<% end %>
</section>