config/routes.rb
Rails.application.routes.draw do
  get 'notifications/link_through'
  resources :posts do
    resources :replies
    resources :likes
  end

  resources :conversations do
    resources :messages
  end


  resources :profiles

  get "search", to: "posts#search"
  get "geolocation", to: "posts#geolocation"
  get "faq", to: "public#faq"
  get "secret", to: "conversations#secret"
  get 'notifications', to: 'notifications#index'
  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through


  devise_for :accounts, :controllers => { :omniauth_callbacks => "omniauth_callbacks", registrations: 'registrations'}
  root "public#main"
end

app/views/layouts/nav/_public.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="#">Freepery <i class='fas fa-frog'></i></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
     <% if account_signed_in? %>
     <li class="nav-item">
        <a class="nav-link">Bentornato <%= current_account.username %> <% if has_role?(:admin) %><font color="red">[ADMINISTRATOR]</font><% end %> </a>
      </li>
     <% end %>
       <li class="nav-item">
        <%= link_to 'Home',root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'FAQ',faq_path, class: "nav-link" %>
      </li>
      <% if account_signed_in? %>
       <li class="nav-item">
        <%= link_to 'Board', posts_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Profilo', profile_path(current_account.id), class: "nav-link" %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/conversations"><i class="fa fa-envelope" aria-hidden="true"></i></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/geolocation"><i class="fa fa-map-marker" aria-hidden="true"></i></a>
      </li>
      <% if current_account.notifications.where(read: false).count == 0 %>
      <li class="nav-item">
        <a class="nav-link" href="/notifications"><i class="fa fa-bell-o" aria-hidden="true"></i></a>
      </li>
      <% else %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"><%= current_account.notifications.where(read: false).count %> <i class="fa fa-bell" aria-hidden="true"></i></a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
        <%= link_to "Centro notifiche", notifications_path , class: "dropdown-item" %>
        <% current_account.notifications.where(read: false).each do |notification| %>
            <%= link_to "#{notification.notified_by.first_name} #{notification.notified_by.last_name} ha #{notification.notice_type} il tuo messaggio", link_through_path(notification), class: "dropdown-item" %>
        <% end %>
        </div>
      </li>
      <% end %>
      <% if has_role?(:admin) %>
      <li class="nav-item">
        <%= link_to 'Conversazioni private', secret_path, class: "nav-link" %>
      </li>
      <% end %>
      <li class="nav-item">
        <%= link_to 'Modifica dati', edit_account_registration_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Esci', destroy_account_session_path, class: "nav-link", method: :delete %>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Accedi", new_account_session_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Iscriviti", new_account_registration_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Accedi con Facebook", account_facebook_omniauth_authorize_path, class: "nav-link" %>
      </li>
    <% end %>
    </ul>
    <% if account_signed_in? %>
    <form class="form-inline my-2 my-lg-0" action="/search">
      <input class="form-control mr-sm-2" name="q" type="text" placeholder="" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Cerca</button>
    </form>
    <% end %>
  </div>
</nav>