config/routes.rb
Rails.application.routes.draw do
  get 'notifications/link_through'
  resources :posts do
    resources :replies
    resources :likes
  end

  resources :conversations do
    resources :messages
  end


  resources :profiles

  get "search", to: "posts#search"
  get "geolocation", to: "posts#geolocation"
  get "faq", to: "public#faq"
  get "secret", to: "conversations#secret"
  get 'notifications', to: 'notifications#index'
  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through


  devise_for :accounts, :controllers => { :omniauth_callbacks => "omniauth_callbacks", registrations: 'registrations'}
  root "public#main"
end

app/models/post.rb
class Post < ApplicationRecord

belongs_to :account, :counter_cache => true
has_one_attached :postimage
has_many :replies, dependent: :destroy
has_many :likes, dependent: :destroy
has_many :notifications, dependent: :destroy

validates :post, presence: true
resourcify

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_account!
  before_action :owned_post, only: [:edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order("created_at DESC")
    @post = Post.new
    @users = Account.all
  end

  def search
        @posts = Post.where("post LIKE ?", "%" + params[:q] + "%")
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = current_account.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
     @post = current_account.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def geolocation
    @users = Account.all_except(current_account.id).near(current_account.address, 100)
    @hash = Gmaps4rails.build_markers(@users) do |user, marker|
        marker.lat user.latitude
        marker.lng user.longitude

    marker.picture({
              :width  => "45",
              :height => "45"
             })

     marker.infowindow render_to_string(:partial => "/posts/info",
        :locals => {:name => user.first_name, :lastname => user.last_name, :birthday=> user.birthday, :id=> user.id, :username=> user.username, :address=> user.address })


    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:post, :postimage)
    end

    def owned_post
        unless current_account == @post.account || current_account.has_role?(:admin)
            flash[:alert] = "Non puoi modificare un post non creato da te!"
            redirect_to posts_path
    end

end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_feed.html.erb
<div class="column is-7">
  <% if account_signed_in? %>
	<article class="media box">
		<figure class="media-left">
			<p class="image is-64x64">
				<%= gravatar_image_tag(current_account.email, size: 64, alt: current_account.name) %>
			</p>
		</figure>
		<div class="media-content">
			 <%= render 'posts/form' %>
		</div>
	</article>
  <% end %>


<% @posts.each do | post | %>
  <div class="box">
  	<article class="media">
  		<div class="media-left">
  			<figure class="image is-64x64">
  				<%= gravatar_image_tag(post.account.email, size: 64, alt: post.account.name) %>
  			</figure>
  		</div>
  		<div class="media-content">
  			<div class="content">
  				<strong><%=link_to(post.account.first_name + " " + post.account.last_name, profile_path(post.account_id) )%></strong><br />
  				<small><%= post.account.username %></small><br/>
  				<p><h3><%= post.post %></h3></p>
                <% if post.postimage.attached? %>
                <%= image_tag(post.postimage, size: "400x500") %>
                <% end %>
                <br>
                <p><em><small>Posted <%= time_ago_in_words(post.created_at) %> ago</small></em></p>
  			</div>
        <nav class="level">
  				<div class="level-left is-mobile">
                    <%= link_to post, class: "level-item" do %>
                     <h1 class="subtitle is-5 has-text-grey"><%= post.replies.count %> commenti <i class="fa fa-heart" aria-hidden="true"></i>   <%= post.likes.count %> "Mi piace"</h1>
                      <% end %>
                </div>
        <% if account_signed_in? && current_account.id == post.account_id || has_role?(:admin) %>
  			<nav class="level">
  				<div class="level-left is-mobile">
  					<%= link_to post, class: "level-item" do %>
  					  <span class="icon"><i class="fa fa-eye" aria-hidden="true"></i></span>
  					<% end %>
  					<%= link_to edit_post_path(post), class: "level-item" do %>
  					  <span class="icon"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></span>
  					<% end %>
  					<%= link_to post, method: :delete, data: { confirm: "Sei sicuro di voler rimuovere il messaggio?" } do %>
                    <span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>
  					<% end %>
  				</div>
  			</nav>
        <% end %>
  		</div>
  	</article>
  </div>
<% end %>
</div>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
<%= f.error_notification %>
<div class="field">
  <div class="control">
    <%= f.input :post, label: "Messaggio", input_html: { class: "textarea "}, wrapper: false, label_html: {class: "label"}, placeholder: "Scrivi un messaggio", autofocus: true %>
     <br>
    <%= f.file_field :postimage %>
  </div>
</div>
<%= f.button :submit, class: "button is-info" , value: "Invia" %>
<% end %>

app/views/posts/_info.html.erb
<style type="text/css">
 #low     { color: red;     }
 #medium  { color: orange;  }
 #high    { color: green;   }
</style>

    <b>Nome:</b> <%= name %><br>
    <b>Cognome:</b> <%= lastname %><br>
    <b>Data di nascita:</b> <%= birthday %><br>
    <b>Username:</b> <%= link_to username, profile_path(id) %><br>
    <b>Luogo:</b> <%= address %><br>

app/views/posts/_profile.html.erb
<div class="column is-one-quarter">
	<nav class="panel">
		<p class="panel-heading">Profilo</p>
		<div class="panel-block">
			<article class="media">
				<div class="media-left">
					<figure class="image is-64x64">
						<%= gravatar_image_tag(current_account.email, size: 64, alt: current_account.name) %>
					</figure>
				</div>
				<div class="media-content">
					<div class="content">
						<p>
							<strong><%= current_account.first_name + " " + current_account.last_name %></strong><br />
							<small><%= current_account.username %></small><br />
                            <small>Compleanno: <%= current_account.birthday %></small>
						</p>
					</div>
				</div>
			</article>
		</div>
		<div class="panel-block">
			<div class="level is-mobile">
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">posts</p>
						<p class="title is-6"><%= current_account.posts.count %></p>
					</div>
				</div>
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Likes</p>
						<p class="title is-6"><%= current_account.likes.count%></p>
					</div>
				</div>
					<div class="level-item has-centered-text">
					<div>
						<p class="heading">Commenti</p>
						<p class="title is-6">9</p>
					</div>
				</div>
			</div>
		</div>
	</nav>
</div>

app/views/posts/_top-users.html.erb
<div class="column is-3">
	<nav class="panel">
		<p class="panel-heading">Utenti più attivi</p>
        <% @users.where("posts_count > 0").order("posts_count DESC").each do | account | %>
        <div class="panel-block">
            <article class="media">
                <div class="media-left">
                    <figure class="image is-32x32">
                        <%= gravatar_image_tag(account.email, size: 64, alt: account.name) %>
                    </figure>
                </div>
                <div class="media-content">
                    <div class="content">
                        <p>
                            <strong><%=link_to(account.first_name + " " + account.last_name, profile_path(account.id))%></strong><br>
                            <small><%= account.username %></small><br/>
                            <small> Posts: <%= account.posts_count %></small><br/>
                        </p>
                    </div>
                </div>
            </article>
        </div>
        <% end %>
        </nav>
    </div>

app/views/posts/_trends.html.erb
<div class="column is-one-quarter">
	<nav class="panel">
		<p class="panel-heading">Trends</p>
		<a class="panel-block">
			Trend 1
		</a>
		<a class="panel-block">
			Trend 2
		</a>
		<a class="panel-block">
			Trend 3
		</a>
		<a class="panel-block">
			Trend 4
		</a>
		<a class="panel-block">
			Trend 5
		</a>
		<a class="panel-block">
			Trend 6
		</a>
	</nav>
</div>

app/views/posts/edit.html.erb
<section class="form-auth text-center">

<h1>Modifica messaggio</h1>

<%= render 'form', post: @post %>
<br>
<%= link_to 'Mostra messaggio', @post %> |
<%= link_to 'Vai alla board', posts_path %>
</section>

app/views/posts/geolocation.html.erb
<section class="form-auth text-center">
<h1>Utenti nelle vicinanze</h1><br>
<div style='width: 800px;'>
        <div id="map" style='width: 800px; height: 400px;'></div>
</div>
</section>

<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ provider: { zoom: 6, center: new google.maps.LatLng(42.938004, 12.621621), mapTypeId: google.maps.MapTypeId.ROADMAP}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    // to center on a marker
    handler.map.centerOn(markers[0]);
// to set the map zoom
    handler.getMap().setZoom(6);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    handler.map.serviceObject.setZoom(6);
});
</script>

app/views/posts/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
       <%= render 'top-users' %>
       <%= render 'feed' %>
    </div>
  </div>
</section>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/search.html.erb
<section class="form-auth text-center">
<h1> Risultati di ricerca</h1>
<br>
<% if @posts.count == 0 %>
    <h2 class="subtitle is-5 has-text-grey">Spiacente, nessun messaggio corrisponde al criterio di ricerca selezionato.</h2>
    <%= link_to 'Vai alla board', posts_path %>
<% else %>
    <h2 class="subtitle is-5 has-text-grey"><%= @posts.count %> messaggi trovati</h2>
    <% @posts.each do | post | %>
      <div class="box">
        <article class="media">
            <div class="media-left">
                <figure class="image is-64x64">
                    <%= gravatar_image_tag(post.account.email, size: 64, alt: post.account.name) %>
                </figure>
            </div>
            <div class="media-content">
                <div class="content">
                    <strong><%=link_to(post.account.first_name + " " + post.account.last_name, profile_path(post.account_id) )%></strong><br />
                    <small><%= post.account.username %></small><br/>
                    <p><h3><%= post.post %></h3></p>
                    <% if post.postimage.attached? %>
                    <%= image_tag(post.postimage) %>
                    <% end %>
                    <br>
                    <p><em><small>Posted <%= time_ago_in_words(post.created_at) %> ago</small></em></p>
                </div>
            <nav class="level">
                    <div class="level-left is-mobile">
                        <%= link_to post, class: "level-item" do %>
                        <h1 class="subtitle is-5 has-text-grey"><%= post.replies.count %> commenti</h1>
                        <% end %>
                        <% if account_signed_in? && current_account.id != post.account_id %>
                        <%= link_to "PM", conversations_path(sender_id: current_account.id, recipient_id: post.account_id), method: 'post', class:"button is-link" %>
                        <% end %>
                    </div>
            <% if account_signed_in? && current_account.id == post.account_id || has_role?(:admin) %>
                <nav class="level">
                    <div class="level-left is-mobile">
                        <%= link_to post, class: "level-item" do %>
                          <span class="icon"><i class="fa fa-eye" aria-hidden="true"></i></span>
                        <% end %>
                        <%= link_to edit_post_path(post), class: "level-item" do %>
                          <span class="icon"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></span>
                        <% end %>
                        <%= link_to post, method: :delete, data: { confirm: "Sei sicuro di voler rimuovere il messaggio?" } do %>
                        <span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>
                        <% end %>
                    </div>
                </nav>
            <% end %>
            </div>
        </article>
      </div>
    <% end %>
    <%= link_to 'Vai alla board', posts_path %>
    </section>
    <% end %>

app/views/posts/show.html.erb
<section class="form-auth text-center">
    <h3 class="title is-2 has-text-black post-author">Post di <%= @post.account.username %></h3>
    <div class="level">
      <div class="level-center">
        <% if account_signed_in? && current_account.id == @post.account_id || has_role?(:admin) %>
        <div class="buttons">
            <%= link_to 'Modifica', edit_post_path(@post), class:'button'%>
            <%= link_to 'Cancella', post_path(@post), method: :delete, data: { confirm: "Cancellare il post?" }, class:'button' %>
        </div>
        <% end %>
      </div>
    </div>

    <div class="content">
    <% if @post.postimage.attached? %>
    <%= image_tag(@post.postimage) %>
    <% end %>
    <br><br>
    <h4><%= @post.post %></h4></div>
    <br>

    <p><i class="fa fa-heart" aria-hidden="true"></i> <%= @post.likes.count %> likes
    <% pre_like = @post.likes.find { |like| like.account_id == current_account.id} %>
    <% if pre_like %>
        <%= button_to 'Non mi piace più', post_like_path(@post, pre_like), method: :delete , class:"button is-link"%>
    <% else %>
        <%= button_to 'Mi piace', post_likes_path(@post), method: :post , class:"button is-link" %>
    <% end %>
    </p>
    </div>
    <br><br>
    <h2 class="subtitle is-5 has-text-grey"><%= @post.replies.count %> commenti</h2>
    <div id="post-replies">
      <%= render @post.replies %>
    </div></div></div><br>
    <hr>
    <br>
    <h3 class="subtitle is-3 has-text-grey">Lascia un commento</h3>
    <% if account_signed_in? %>
      <%= render 'replies/form' %>
    <% else %>
    <p>Per rispondere devi <%= link_to 'login', new_account_session_path %>. Don't have an account?
      <%= link_to 'Sign up', new_account_registration_path %> for one.</p>
    <% end %>



</div>
</section>